create database FOREIGN_TEST;
use FOREIGN_TEST;
create table Adding(a int, b int, c char(10));
create table Minus(a char(10), b char(8), c int, d int);
create table Multiply(a int , b char(8), c int);
alter table Minus add constraint Foreign1 foreign key (c, d) references Adding(a, b);
alter table Multiply add constraint Foreign2 foreign key (a, c) references Adding(b, a);
insert into Minus values ("test", "test2", 1, 2);
insert into Multiply values (1, "swh", 4);
insert into Adding values (1, 2, "4");
insert into Minus values ("test", "test2", 1, 2);
insert into Minus values ("test", "test2", 1, 2);
select * from Adding;
desc Adding;
alter table Minus drop foreign key Foreign1;
insert into Minus values ("test", "test2", 3, 4);
select * from Minus;
alter table Minus add constraint Foreign1 foreign key (c, d) references Adding(a, b);
delete from Minus where c = 3;
select * from Minus;
select * from Adding;
alter table Minus add constraint Foreign1 foreign key (c, d) references Adding(a, b);
insert into Minus values ("a", "b", 5, 6);
select * from Minus;
delete from Adding where a = 1;
select * from Adding;
drop database FOREIGN_TEST;